account/urls.py
from django.urls import path
#from django.contrib.auth import views as auth_views
from account.views import MyPasswordResetView, MyPasswordResetConfirmView

from . import views

app_name = 'account'

urlpatterns = [
    path('', views.signin, name='signin'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('password_reset/', MyPasswordResetView.as_view(), name="password_reset"),
    path('password_reset_confirm/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    #path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    #path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    #path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    #path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from datetime import datetime
from backend import views as indexView
from rank import views as rankView
if settings.STARTING < datetime.now() < settings.ENDING:
    urlpatterns = [
        path('', indexView.index, name = 'index'),
        path('admin/', admin.site.urls),
        path('notice/', include('notice.urls')),
        path('account/', include('account.urls')),
        path('challenge/', include('prob.urls')),
        path('rank/', rankView.ListRank, name = 'rank'),
        ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
else:
    urlpatterns = [
        path('', indexView.beforeStart, name = 'index'),
        path('admin/', admin.site.urls),
    ]

prob/urls.py
from django.urls import path

from . import views

app_name = 'chall'

urlpatterns = [
   path('', views.ListProb, name='challenge'),
   path('select/', views.DetailProb, name='prob_select'),
   path('flag/',views.flagProb, name='flag_auth'),
]

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {% load static %}<link rel="stylesheet" href="{% static '/dist/css/bootstrap.css' %}">
        <style type="text/css">
        .btn-nav{
        padding:0 10px;
        }
        .nav-item{
        margin-left:30px;
        }
        .nav-tabs{
        border-bottom:none;
        margin:auto 0;
        }
        {% block style %}{% endblock %}
        </style>
    </head>
    <body>
        <header>
            <nav class="navbar  navbar-dark fixed-top bg-dark">
                <a class=" navbar-brand" href="/">YISF</a>
                    {% if user.is_authenticated %}
                <div class="mr-auto">
                    <ul class="nav-tabs navbar">
                        <li class="navbar-nav nav-item">
                            <a class="nav-link btn btn-nav" href="/notice">공지</a>
                        </li>
                        <li class="navbar-nav nav-item">
                            <a class="nav-link btn btn-nav" href="/challenge">문제</a>
                        </li>
                        <li class="navbar-nav nav-item">
                            <a class="nav-link btn btn-nav" href="/rank">순위</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <h5 class="navbar navbar-text ">login info : {{user.nick}}</h5>
                    <a class="btn btn-danger" href="{% url 'account:signout' %}">로그아웃</a>
                </div>
                    {% else %}
                <div>
                    <a class="btn btn-danger" href="{% url 'account:signin' %}">로그인</a>
                </div>
                    {% endif %}
                    {% if user.is_admin %}
                <div class="navbar">
                    <a class="btn btn-danger" href="/admin">관리자 페이지</a>
                </div>
                    {% endif %}

            </nav>
        </header>
        <br><br><br><br>
        {% block content %}
        {% endblock %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.js"></script>
        <script type="text/javascript" src="{% static '/dist/js/bootstrap.js' %}"></script>
        {% block script %}{% endblock %}
    <body>
</html>

templates/before.html
<html>
    <head>
        <meta charset="utf8">
        <title>대회 시간이 아닙니다.</title>
        <style>
            .title{
                text-align:center;
                margin-top: 12%;
            }
        </style>
    </head>
    <body>
        <div class="title">
            <h1>아직 대회 시간이 아닙니다!!</h1>
        </div>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block title %} main page {% endblock %}
{% block content %}
{{content}}
<br>
{% endblock %}