account/urls.py
from django.urls import path
#from django.contrib.auth import views as auth_views
from account.views import MyPasswordResetView, MyPasswordResetConfirmView

from . import views

app_name = 'account'

urlpatterns = [
    path('', views.signin, name='signin'),
    path('signin/', views.signin, name='signin'),
    path('signout/', views.signout, name='signout'),
    path('password_reset/', MyPasswordResetView.as_view(), name="password_reset"),
    path('password_reset_confirm/<uidb64>/<token>/', MyPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    #path('password_reset/', auth_views.PasswordResetView.as_view(), name="password_reset"),
    #path('password_reset_done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    #path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    #path('password_reset_complete/', auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from datetime import datetime
from backend import views as indexView
from rank import views as rankView
if settings.STARTING < datetime.now() < settings.ENDING:
    urlpatterns = [
        path('', indexView.index, name = 'index'),
        path('admin/', admin.site.urls),
        path('notice/', include('notice.urls')),
        path('account/', include('account.urls')),
        path('challenge/', include('prob.urls')),
        path('rank/', rankView.ListRank, name = 'rank'),
        ] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
else:
    urlpatterns = [
        path('', indexView.beforeStart, name = 'index'),
        path('admin/', admin.site.urls),
    ]

prob/urls.py
from django.urls import path

from . import views

app_name = 'chall'

urlpatterns = [
   path('', views.ListProb, name='challenge'),
   path('select/', views.DetailProb, name='prob_select'),
   path('flag/',views.flagProb, name='flag_auth'),
]

templates/challenge/listProb.html
{% extends 'base.html' %}
{% block title %}문제{% endblock %}
{% block style %}
.set {
width:750px;
margin:0 auto;
}
th {
text-align: center;
}
td {
text-align: center;
}
.modal-score{
padding:10px;
margin-bottom:0;
}
.flag-submit{
margin:0 auto 0 0;
}
.modal-link{
padding:0 10px;
text-align:right;
}
.modal-file{
padding:0 10px;
text-align:right;
}
.modal-content{
margin-top: 10em;
}
{% endblock %}
{% block content %}
<div class="set">
{% if problist %}
<table class="table">
    <thead>
        <tr>
            <th width="100">score</th>
            <th width="500">title</th>
            <th width="150">branch</th>
        </tr>
    </thead>
    <tbody>
    {% for prob in problist %}
        <tr>
            <td width="100">{{prob.pscore}}</td>
            <td width="500" class="chall btn" name="{{prob.id}}">{{prob.title}}</td>
            <td width="150">{{prob.tag}}</td>
        </tr>
    {% endfor %}
    <tbody>
</table>
{% else %}
<p>현재 공개된 문제가 없습니다.</p>
{% endif %}
</div>
<div class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- header -->
            <div class="modal-header">
                <!-- title -->
                <h4 class="modal-title">Header</h4>
                <!-- score -->
                <h6 class="modal-score">score</h6>
                <!-- close button -->
                <button type="button" class="close" data-dismiss="modal">×</button>
            </div>
            <!-- body -->
            <div class="modal-body">
            Body
            </div>
            <div class="modal-link"></div>
            <div class="modal-file"></div>
            <!-- Footer -->
            <div class="modal-footer">
                <form class="flag-submit">
                    <input class="modal-input" type="text" size="40" name="flag" placeholder="flag 입력">
                    <input type="button" id="flagform" class="btn btn-default" value="제출">
                </form>
                <button type="button" class="btn btn-default" data-dismiss="modal">닫기</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script type="text/javascript">
    var pk = null;
    var token = null;
    $(".chall").click(function(){
        pk = $(this).attr('name')
        $.ajax({
            type: "POST",
            url: "{% url 'chall:prob_select' %}",
            data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: "json",
            success: function(response){
                $(".modal-title").text(response.title);
                $(".modal-score").text(response.score);
                $(".modal-body").text(response.description);
                token = response.token;
                if(response.link){ $(".modal-link").html('<a type="button" class="modal-link btn btn-default" href="'+response.link+'" target="_blank">link</a>');}
                else{ $(".modal-link").html('<a type="hidden"></a>');}
                if(response.file){ $(".modal-file").html('<a type="button" class="modal-file btn btn-default" href="'+response.file+'" target="_blank">file download</a>');}
                else{ $(".modal-file").html('<a type="hidden"></a>');}
                $('div.modal').modal();
            },
            error: function(request, status, error){
                alert("error");
                window.location.replace("{% url 'account:signin' %}");
            },
        });
    })
    $("#flagform").click(function(){
        if (pk == null || token == null){
            alert("error");
        } else{
            var value = $('input:text').val();
            $.ajax({
                type: "POST",
                url: "{% url 'chall:flag_auth' %}",
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}', 'flag': decodeURI(value)},
                dataType: "json",
                success: function(response){
                    if(response.auth){
                        alert("congraturation!");
                        window.location.reload();
                    } else{
                        alert("fail to solve");
                    }
                },
                error: function(){
                alert("error");
                window.location.replace("{% url 'account:signin' %}");
                },
            });
        }
    })
</script>
{% endblock %}